export enum CHECKBOX_TYPES {
  SELECTED = 'SELECTED',
  UNSELECTED = 'UNSELECTED',
}

export enum CHECKBOX_STATE_TYPES {
  ENABLED = 'ENABLED',
  HOVER = 'HOVER',
  PRESSED = 'PRESSED',
  DISABLED = 'DISABLED',
}
