// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock_service

import (
	context "context"

	models "github.com/Zampfi/application-platform/services/api/db/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockConnectionServiceStore is an autogenerated mock type for the ConnectionServiceStore type
type MockConnectionServiceStore struct {
	mock.Mock
}

type MockConnectionServiceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionServiceStore) EXPECT() *MockConnectionServiceStore_Expecter {
	return &MockConnectionServiceStore_Expecter{mock: &_m.Mock}
}

// CreateConnection provides a mock function with given fields: ctx, connection
func (_m *MockConnectionServiceStore) CreateConnection(ctx context.Context, connection *models.CreateConnectionParams) (uuid.UUID, error) {
	ret := _m.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnection")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateConnectionParams) (uuid.UUID, error)); ok {
		return rf(ctx, connection)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateConnectionParams) uuid.UUID); ok {
		r0 = rf(ctx, connection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateConnectionParams) error); ok {
		r1 = rf(ctx, connection)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionServiceStore_CreateConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnection'
type MockConnectionServiceStore_CreateConnection_Call struct {
	*mock.Call
}

// CreateConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - connection *models.CreateConnectionParams
func (_e *MockConnectionServiceStore_Expecter) CreateConnection(ctx interface{}, connection interface{}) *MockConnectionServiceStore_CreateConnection_Call {
	return &MockConnectionServiceStore_CreateConnection_Call{Call: _e.mock.On("CreateConnection", ctx, connection)}
}

func (_c *MockConnectionServiceStore_CreateConnection_Call) Run(run func(ctx context.Context, connection *models.CreateConnectionParams)) *MockConnectionServiceStore_CreateConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateConnectionParams))
	})
	return _c
}

func (_c *MockConnectionServiceStore_CreateConnection_Call) Return(_a0 uuid.UUID, _a1 error) *MockConnectionServiceStore_CreateConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionServiceStore_CreateConnection_Call) RunAndReturn(run func(context.Context, *models.CreateConnectionParams) (uuid.UUID, error)) *MockConnectionServiceStore_CreateConnection_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConnectionPolicy provides a mock function with given fields: ctx, connectionId, audienceType, audienceId, privilege
func (_m *MockConnectionServiceStore) CreateConnectionPolicy(ctx context.Context, connectionId uuid.UUID, audienceType models.AudienceType, audienceId uuid.UUID, privilege models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, connectionId, audienceType, audienceId, privilege)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnectionPolicy")
	}

	var r0 *models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, connectionId, audienceType, audienceId, privilege)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) *models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, connectionId, audienceType, audienceId, privilege)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) error); ok {
		r1 = rf(ctx, connectionId, audienceType, audienceId, privilege)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionServiceStore_CreateConnectionPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnectionPolicy'
type MockConnectionServiceStore_CreateConnectionPolicy_Call struct {
	*mock.Call
}

// CreateConnectionPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionId uuid.UUID
//   - audienceType models.AudienceType
//   - audienceId uuid.UUID
//   - privilege models.ResourcePrivilege
func (_e *MockConnectionServiceStore_Expecter) CreateConnectionPolicy(ctx interface{}, connectionId interface{}, audienceType interface{}, audienceId interface{}, privilege interface{}) *MockConnectionServiceStore_CreateConnectionPolicy_Call {
	return &MockConnectionServiceStore_CreateConnectionPolicy_Call{Call: _e.mock.On("CreateConnectionPolicy", ctx, connectionId, audienceType, audienceId, privilege)}
}

func (_c *MockConnectionServiceStore_CreateConnectionPolicy_Call) Run(run func(ctx context.Context, connectionId uuid.UUID, audienceType models.AudienceType, audienceId uuid.UUID, privilege models.ResourcePrivilege)) *MockConnectionServiceStore_CreateConnectionPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.AudienceType), args[3].(uuid.UUID), args[4].(models.ResourcePrivilege))
	})
	return _c
}

func (_c *MockConnectionServiceStore_CreateConnectionPolicy_Call) Return(_a0 *models.ResourceAudiencePolicy, _a1 error) *MockConnectionServiceStore_CreateConnectionPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionServiceStore_CreateConnectionPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)) *MockConnectionServiceStore_CreateConnectionPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionByID provides a mock function with given fields: ctx, id
func (_m *MockConnectionServiceStore) GetConnectionByID(ctx context.Context, id uuid.UUID) (*models.Connection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionByID")
	}

	var r0 *models.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Connection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Connection); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionServiceStore_GetConnectionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionByID'
type MockConnectionServiceStore_GetConnectionByID_Call struct {
	*mock.Call
}

// GetConnectionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockConnectionServiceStore_Expecter) GetConnectionByID(ctx interface{}, id interface{}) *MockConnectionServiceStore_GetConnectionByID_Call {
	return &MockConnectionServiceStore_GetConnectionByID_Call{Call: _e.mock.On("GetConnectionByID", ctx, id)}
}

func (_c *MockConnectionServiceStore_GetConnectionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockConnectionServiceStore_GetConnectionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConnectionServiceStore_GetConnectionByID_Call) Return(_a0 *models.Connection, _a1 error) *MockConnectionServiceStore_GetConnectionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionServiceStore_GetConnectionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Connection, error)) *MockConnectionServiceStore_GetConnectionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionPolicies provides a mock function with given fields: ctx, connectionId
func (_m *MockConnectionServiceStore) GetConnectionPolicies(ctx context.Context, connectionId uuid.UUID) ([]models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, connectionId)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionPolicies")
	}

	var r0 []models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, connectionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, connectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, connectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionServiceStore_GetConnectionPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionPolicies'
type MockConnectionServiceStore_GetConnectionPolicies_Call struct {
	*mock.Call
}

// GetConnectionPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionId uuid.UUID
func (_e *MockConnectionServiceStore_Expecter) GetConnectionPolicies(ctx interface{}, connectionId interface{}) *MockConnectionServiceStore_GetConnectionPolicies_Call {
	return &MockConnectionServiceStore_GetConnectionPolicies_Call{Call: _e.mock.On("GetConnectionPolicies", ctx, connectionId)}
}

func (_c *MockConnectionServiceStore_GetConnectionPolicies_Call) Run(run func(ctx context.Context, connectionId uuid.UUID)) *MockConnectionServiceStore_GetConnectionPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConnectionServiceStore_GetConnectionPolicies_Call) Return(_a0 []models.ResourceAudiencePolicy, _a1 error) *MockConnectionServiceStore_GetConnectionPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionServiceStore_GetConnectionPolicies_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.ResourceAudiencePolicy, error)) *MockConnectionServiceStore_GetConnectionPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnections provides a mock function with given fields: ctx
func (_m *MockConnectionServiceStore) GetConnections(ctx context.Context) ([]models.Connection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnections")
	}

	var r0 []models.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Connection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Connection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionServiceStore_GetConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnections'
type MockConnectionServiceStore_GetConnections_Call struct {
	*mock.Call
}

// GetConnections is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConnectionServiceStore_Expecter) GetConnections(ctx interface{}) *MockConnectionServiceStore_GetConnections_Call {
	return &MockConnectionServiceStore_GetConnections_Call{Call: _e.mock.On("GetConnections", ctx)}
}

func (_c *MockConnectionServiceStore_GetConnections_Call) Run(run func(ctx context.Context)) *MockConnectionServiceStore_GetConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConnectionServiceStore_GetConnections_Call) Return(_a0 []models.Connection, _a1 error) *MockConnectionServiceStore_GetConnections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionServiceStore_GetConnections_Call) RunAndReturn(run func(context.Context) ([]models.Connection, error)) *MockConnectionServiceStore_GetConnections_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnectionPolicy provides a mock function with given fields: ctx, connectionId, audienceId, privilege
func (_m *MockConnectionServiceStore) UpdateConnectionPolicy(ctx context.Context, connectionId uuid.UUID, audienceId uuid.UUID, privilege models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, connectionId, audienceId, privilege)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnectionPolicy")
	}

	var r0 *models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, connectionId, audienceId, privilege)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) *models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, connectionId, audienceId, privilege)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) error); ok {
		r1 = rf(ctx, connectionId, audienceId, privilege)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionServiceStore_UpdateConnectionPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnectionPolicy'
type MockConnectionServiceStore_UpdateConnectionPolicy_Call struct {
	*mock.Call
}

// UpdateConnectionPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionId uuid.UUID
//   - audienceId uuid.UUID
//   - privilege models.ResourcePrivilege
func (_e *MockConnectionServiceStore_Expecter) UpdateConnectionPolicy(ctx interface{}, connectionId interface{}, audienceId interface{}, privilege interface{}) *MockConnectionServiceStore_UpdateConnectionPolicy_Call {
	return &MockConnectionServiceStore_UpdateConnectionPolicy_Call{Call: _e.mock.On("UpdateConnectionPolicy", ctx, connectionId, audienceId, privilege)}
}

func (_c *MockConnectionServiceStore_UpdateConnectionPolicy_Call) Run(run func(ctx context.Context, connectionId uuid.UUID, audienceId uuid.UUID, privilege models.ResourcePrivilege)) *MockConnectionServiceStore_UpdateConnectionPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(models.ResourcePrivilege))
	})
	return _c
}

func (_c *MockConnectionServiceStore_UpdateConnectionPolicy_Call) Return(_a0 *models.ResourceAudiencePolicy, _a1 error) *MockConnectionServiceStore_UpdateConnectionPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionServiceStore_UpdateConnectionPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)) *MockConnectionServiceStore_UpdateConnectionPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnectionServiceStore creates a new instance of MockConnectionServiceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionServiceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionServiceStore {
	mock := &MockConnectionServiceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
