// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock_postgres

import (
	context "context"

	models "github.com/Zampfi/application-platform/services/api/pkg/dataplatform/models"
	mock "github.com/stretchr/testify/mock"
)

// MockPostgresSqlService is an autogenerated mock type for the PostgresSqlService type
type MockPostgresSqlService struct {
	mock.Mock
}

type MockPostgresSqlService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgresSqlService) EXPECT() *MockPostgresSqlService_Expecter {
	return &MockPostgresSqlService_Expecter{mock: &_m.Mock}
}

// Query provides a mock function with given fields: ctx, table, query, args
func (_m *MockPostgresSqlService) Query(ctx context.Context, table string, query string, args ...interface{}) (models.QueryResult, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, table, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 models.QueryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...interface{}) (models.QueryResult, error)); ok {
		return rf(ctx, table, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...interface{}) models.QueryResult); ok {
		r0 = rf(ctx, table, query, args...)
	} else {
		r0 = ret.Get(0).(models.QueryResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...interface{}) error); ok {
		r1 = rf(ctx, table, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostgresSqlService_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockPostgresSqlService_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - table string
//   - query string
//   - args ...interface{}
func (_e *MockPostgresSqlService_Expecter) Query(ctx interface{}, table interface{}, query interface{}, args ...interface{}) *MockPostgresSqlService_Query_Call {
	return &MockPostgresSqlService_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, table, query}, args...)...)}
}

func (_c *MockPostgresSqlService_Query_Call) Run(run func(ctx context.Context, table string, query string, args ...interface{})) *MockPostgresSqlService_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockPostgresSqlService_Query_Call) Return(_a0 models.QueryResult, _a1 error) *MockPostgresSqlService_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostgresSqlService_Query_Call) RunAndReturn(run func(context.Context, string, string, ...interface{}) (models.QueryResult, error)) *MockPostgresSqlService_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostgresSqlService creates a new instance of MockPostgresSqlService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgresSqlService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgresSqlService {
	mock := &MockPostgresSqlService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
