import { GridOptions } from 'ag-grid-community';
import {
  ADCB_SVG,
  ADYEN,
  AFTERPAY,
  ALRAJI_SVG,
  AMERICAN_EXPRESS,
  APPLE_PAY,
  ARB_SA,
  ASPIRE_PNG,
  AXIS_IND,
  BAB_KSA,
  BAE_JOR,
  BANKING_CIRCLE,
  BARCLAYS,
  BLOOM_BANK,
  BMO,
  BNQMISR_EG,
  BNY_PNG,
  BOB_IRQ,
  BOP_PSE,
  CASH_APP,
  CHASE_SVG,
  CHECKOUT,
  CIB_EG,
  CITI_BANK,
  CLEARWATER,
  CROSSRIVER,
  DANSKE,
  DEFAULT_BANK,
  DINERS_CLUB,
  DISCOVER,
  ENBD_SVG,
  FAB_SVG,
  GIB_SVG,
  GREEN_CHECK_ICON,
  HDFC_SVG,
  HSBC_SVG,
  ICICI_IN,
  JCB,
  JSB_PAK,
  LEAD_BANK,
  M_AND_T_BANK,
  MASHREQ_SVG,
  MASTERCARD,
  MERCURY,
  NBI_KUR,
  NBK_KWT,
  PASHA,
  PAYPAL,
  QNB_QAT,
  RAIFFEISEN,
  RED_ALERT_ICON,
  SBI_IN,
  STRIPE,
  SVB_PNG,
  TRISTATE,
  TRUIST,
  TURKIYE_IS_BANKASI,
  UNICREDIT,
  UNION_PAY,
  VISA,
  WILMINGTON_TRUST,
} from 'constants/icons';

export const PIVOT_REF = '__REF';
export const NESTING_LEVEL_INFIX = '_LEVEL_';
export const GROUPING_COL_NAME_PREFIX = 'GROUPING_DEPTH_';
export const ROOT_LEVEL_TITLE = 'Total';
export enum PINNED_DIRECTION {
  LEFT = 'left',
  RIGHT = 'right',
}

export enum PIVOT_REF_TYPES {
  RECONCILLIATION = 'Reconciliation Data',
  TAGS = 'Tag',
}

export const COL_MIN_WIDTH = 210;
export const PINNED_COL_WIDTH = 380;
export const PIVOT_HEADER_HEIGHT = 93;
export const PIVOT_GROUP_HEADER_HEIGHT = 42;
export const ROW_HEIGHT = 42;
export const GRAND_ROW_TOTAL_POSITION = 'bottom';

export enum RECON_STATUS_TYPES {
  SETTLED = 'settled',
  MISSING_FROM_ACQUIRER = 'missing_from_acquirer',
  MISSING_FROM_PG = 'missing_from_pg',
  AMOUNT_MISMATCH = 'amount_mismatch',
  MISSING_FROM_INTERNAL = 'missing_from_internal',
  MISSING_FROM_STRIP = 'missing_from_stripe',
  MISSING_FROM_PARTNER = 'missing_from_partner',
  MISSING_FROM_NETSUITE = 'missing_from_netsuite',
}

export enum RECON_BANK_ICONS {
  CHECKOUT = 'checkout',
  ADYEN = 'adyen',
  APPLE_PAY_AMERICAN_EXPRESS = 'Apple Pay - American Express',
  APPLE_PAY_DISCOVER = 'Apple Pay - Discover',
  APPLE_PAY_MASTERCARD = 'Apple Pay - MasterCard',
  APPLE_PAY_VISA = 'Apple Pay - Visa',
  DISCOVER = 'Discover',
  MASTERCARD = 'MasterCard',
  PAYPAL = 'PayPal',
  VISA = 'Visa',
  AMERICAN_EXPRESS = 'American Express',
  DINERS_CLUB = 'Diners Club',
  JCB = 'JCB',
  AFTERPAY = 'Afterpay',
  UNION_PAY = 'UnionPay',
  CASHAPP = 'Cashapp',
}

export const getReconStatusIcon = (status: RECON_STATUS_TYPES): string => {
  switch (status) {
    case RECON_STATUS_TYPES.SETTLED:
      return GREEN_CHECK_ICON;
    case RECON_STATUS_TYPES.MISSING_FROM_ACQUIRER:
    case RECON_STATUS_TYPES.MISSING_FROM_INTERNAL:
    case RECON_STATUS_TYPES.MISSING_FROM_PG:
    case RECON_STATUS_TYPES.MISSING_FROM_STRIP:
    case RECON_STATUS_TYPES.MISSING_FROM_PARTNER:
    case RECON_STATUS_TYPES.MISSING_FROM_NETSUITE:
    case RECON_STATUS_TYPES.AMOUNT_MISMATCH:
      return RED_ALERT_ICON;
    default:
      return GREEN_CHECK_ICON;
  }
};

export const RECON_BANK_ICONS_MAPPING: Record<RECON_BANK_ICONS, string> = {
  [RECON_BANK_ICONS.CHECKOUT]: CHECKOUT,
  [RECON_BANK_ICONS.ADYEN]: ADYEN,
  [RECON_BANK_ICONS.APPLE_PAY_AMERICAN_EXPRESS]: APPLE_PAY,
  [RECON_BANK_ICONS.APPLE_PAY_DISCOVER]: APPLE_PAY,
  [RECON_BANK_ICONS.APPLE_PAY_MASTERCARD]: APPLE_PAY,
  [RECON_BANK_ICONS.APPLE_PAY_VISA]: APPLE_PAY,
  [RECON_BANK_ICONS.DISCOVER]: DISCOVER,
  [RECON_BANK_ICONS.MASTERCARD]: MASTERCARD,
  [RECON_BANK_ICONS.PAYPAL]: PAYPAL,
  [RECON_BANK_ICONS.VISA]: VISA,
  [RECON_BANK_ICONS.AMERICAN_EXPRESS]: AMERICAN_EXPRESS,
  [RECON_BANK_ICONS.DINERS_CLUB]: DINERS_CLUB,
  [RECON_BANK_ICONS.JCB]: JCB,
  [RECON_BANK_ICONS.AFTERPAY]: AFTERPAY,
  [RECON_BANK_ICONS.UNION_PAY]: UNION_PAY,
  [RECON_BANK_ICONS.CASHAPP]: CASH_APP,
};

export const PIVOT_TABLE_THEME_PARAMS = {
  fontFamily: { googleFont: 'Inter' },
  rowHoverColor: '#FAFAFA',
  rowHeight: ROW_HEIGHT,
};

export const PIVOT_GRID_OPTIONS: GridOptions = {
  pivotMode: true,
  suppressContextMenu: true,
  suppressMenuHide: false,
  suppressRowDrag: true,
  suppressMovableColumns: true,
  suppressCellFocus: true,
  maintainColumnOrder: true,
  suppressDragLeaveHidesColumns: true,
  groupMaintainOrder: true,
  scrollbarWidth: 0,
  animateRows: false,
  suppressGroupRowsSticky: true,
  enableStrictPivotColumnOrder: true,
  suppressStickyTotalRow: true,
  suppressHeaderFocus: true,
  suppressAggFuncInHeader: true,
  suppressRowTransform: true,
  autoSizeStrategy: {
    type: 'fitGridWidth',
  },
};

export const BANK_NAME_ICON_MAPPING: Record<string, { name: string; icon: string }> = {
  ADCB_SME_UAE: { name: 'ADCB Procash Business Banking', icon: ADCB_SVG },
  ALRAJHI_KSA: { name: 'Al Rajhi Bank', icon: ALRAJI_SVG },
  ASPIRE_SG: { name: 'Aspire Bank', icon: ASPIRE_PNG },
  AXIS_IND: { name: 'Axis Bank', icon: AXIS_IND },
  BCL_USA: { name: 'Banking Circle', icon: BANKING_CIRCLE },
  BMO_USA: { name: 'BMO', icon: BMO },
  BNY: { name: 'Bank of New York Mellon', icon: BNY_PNG },
  BNQMISR_EG: { name: 'Banque Misr', icon: BNQMISR_EG },
  BR_USA: { name: 'Barclays', icon: BARCLAYS },
  BAE_JOR: { name: 'Bank Al Etihad', icon: BAE_JOR },
  CB_CZE: { name: 'Citibank, N.A. CZE', icon: CITI_BANK },
  CB_FIN: { name: 'Citibank, N.A. FIN', icon: CITI_BANK },
  CB_GBR: { name: 'Citibank, N.A. GBR', icon: CITI_BANK },
  CB_HUN: { name: 'Citibank, N.A. HUN', icon: CITI_BANK },
  CB_BHR: { name: 'Citibank, N.A. BHR', icon: CITI_BANK },
  CB_IRL: { name: 'Citibank, N.A. IRL', icon: CITI_BANK },
  CB_JPN: { name: 'Citibank, N.A. JPN', icon: CITI_BANK },
  CB_LUX: { name: 'Citibank, N.A. LUX', icon: CITI_BANK },
  CB_ISR: { name: 'Citibank, N.A. ISR', icon: CITI_BANK },
  CB_EGY: { name: 'Citibank, N.A. EGY', icon: CITI_BANK },
  CB_JOR: { name: 'Citibank, N.A. JOR', icon: CITI_BANK },
  CB_KWT: { name: 'Citibank, N.A. KWT', icon: CITI_BANK },
  CB_MAR: { name: 'Citibank, N.A. MAR', icon: CITI_BANK },
  CB_PAK: { name: 'Citibank, N.A. PAK', icon: CITI_BANK },
  CB_QAT: { name: 'Citibank, N.A. QAT', icon: CITI_BANK },
  CB_UAE: { name: 'Citibank, N.A. UAE', icon: CITI_BANK },
  CB_GRC: { name: 'Citibank, N.A. GRC', icon: CITI_BANK },
  CB_KAZ: { name: 'Citibank, N.A. KAZ', icon: CITI_BANK },
  CB_SVK: { name: 'Citibank, N.A. SVK', icon: CITI_BANK },
  CB_DEU: { name: 'Citibank, N.A. DEU', icon: CITI_BANK },
  CB_DZA: { name: 'CITI Bank', icon: CITI_BANK },
  CIB_EG: { name: 'Commecial International Bank', icon: CIB_EG },
  CLEARWATER: { name: 'Clearwater', icon: CLEARWATER },
  CRB_USA: { name: 'Cross River Bank', icon: CROSSRIVER },
  DB_FIN: { name: 'Danske Bank FIN', icon: DANSKE },
  DB_GBR: { name: 'Danske Bank GBR', icon: DANSKE },
  DB_NOR: { name: 'Danske Bank NOR', icon: DANSKE },
  DB_POL: { name: 'Danske Bank POL', icon: DANSKE },
  DB_ROU: { name: 'DANSKE', icon: DANSKE },
  ENBD_SME_UAE: { name: 'Emirates NBD BusinessOnline', icon: ENBD_SVG },
  ENBD_UAE: { name: 'Emirates NBD Bank', icon: ENBD_SVG },
  FAB_SME_UAE: { name: 'FABeAccess (including iBanking)', icon: FAB_SVG },
  FAB_UAE: { name: 'First Abu Dhabi Bank', icon: FAB_SVG },
  GIB_KSA: { name: 'Gulf International Bank, Saudi', icon: GIB_SVG },
  HDFC_IN: { name: 'Hdfc Bank', icon: HDFC_SVG },
  HSBC_IN: { name: 'HSBC India', icon: HSBC_SVG },
  HSBC_MU: { name: 'HSBC Mauritius', icon: HSBC_SVG },
  HSBC_UAE: { name: 'HSBC UAE', icon: HSBC_SVG },
  HSBC_UK: { name: 'Hsbc United Kingdom', icon: HSBC_SVG },
  ICICI_IN: { name: 'Icici Bank', icon: ICICI_IN },
  IS_TR: { name: 'İşbank', icon: TURKIYE_IS_BANKASI },
  JPMC_CA: { name: 'JPMorgan Chase Bank, NA Canada', icon: CHASE_SVG },
  JPMC_FRA: { name: 'JPMorgan Chase FR', icon: CHASE_SVG },
  JPMC_GSP: { name: 'JPMorgan Chase SG', icon: CHASE_SVG },
  JPMC_MEX: { name: 'JPMorgan Chase Bank', icon: CHASE_SVG },
  JPM_SG: { name: 'JPMorgan Chase Bank N.A., Singapore Branch', icon: CHASE_SVG },
  JPMC_US: { name: 'JPMorgan Chase Bank, N.A. (SW)', icon: CHASE_SVG },
  JPMC_NLD: { name: 'JPMorgan Chase Netherlands', icon: CHASE_SVG },
  JPMC_SGP: { name: 'JPMorgan Chase SG', icon: CHASE_SVG },
  JPMC_USA: { name: 'J.P. Morgan Chase Bank', icon: CHASE_SVG },
  JPMC_GER: { name: 'JPMorgan Chase Bank', icon: CHASE_SVG },
  JPMC_DEU: { name: 'JPMorgan AG Frankfurt', icon: CHASE_SVG },
  JPMC_AUS: { name: 'JPMorgan Chase Bank, NA Sydney', icon: CHASE_SVG },
  JPM_GB: { name: 'JPMorgan Chase Bank', icon: CHASE_SVG },
  JPM_USA: { name: 'JPMorgan Chase Bank', icon: CHASE_SVG },
  JPMC_BRA: { name: 'Banco JPMorgan S.A.', icon: CHASE_SVG },
  JPMC_JAP: { name: 'JPMorgan Chase Bank', icon: CHASE_SVG },
  JPMC_JPN: { name: 'JPMorgan Chase Bank, NA Tokyo', icon: CHASE_SVG },
  JPMC_BR: { name: 'DDT BR - Savings (9947)', icon: CHASE_SVG },
  LB_USA: { name: 'Lead Bank', icon: LEAD_BANK },
  MT_USA: { name: 'M&T Bank', icon: M_AND_T_BANK },
  PB_AZE: { name: 'PASHA Bank AZE', icon: PASHA },
  RBI_ALB: { name: 'Raiffeisen Bank International ALB', icon: RAIFFEISEN },
  RBI_BRB: { name: 'RAIFFEISEN', icon: RAIFFEISEN },
  SAB_KSA: { name: 'Saudi Awwal Bank', icon: DEFAULT_BANK },
  SBI_IN: { name: 'Sbi Bank', icon: SBI_IN },
  SVB_USA: { name: 'Silicon Valley Bank', icon: SVB_PNG },
  TS_USA: { name: 'Truist', icon: TRUIST },
  UC_HRV: { name: 'UniCredit HRV', icon: UNICREDIT },
  UC_SRB: { name: 'UniCredit SRB', icon: UNICREDIT },
  WT_USA: { name: 'Wilmington Trust', icon: WILMINGTON_TRUST },
  GB_TUR: { name: 'Garanti Bank', icon: DEFAULT_BANK },
  GIB: { name: 'GIB BANK', icon: GIB_SVG },
  SPK_MKD: { name: 'SPARKASSE', icon: DEFAULT_BANK },
  SNB_KSA: { name: 'Saudi National Bank (SNB)', icon: DEFAULT_BANK },
  JPMC_NZ: { name: 'DD NZ - Savings-Sweep (1128)', icon: DEFAULT_BANK },
  FB_PAK: { name: 'Faysal Bank', icon: DEFAULT_BANK },
  CB_GB: { name: 'Clearbank', icon: DEFAULT_BANK },
  SMBC_JPN: { name: 'Sumitomo Mitsui Banking Corporation JPN', icon: DEFAULT_BANK },
  UC_SVN: { name: 'UniCredit SVN', icon: UNICREDIT },
  BBK_BH: { name: 'BBK, Bahrain', icon: DEFAULT_BANK },
  MIZUHO: { name: 'Mizuho Bank, Ltd.', icon: DEFAULT_BANK },
  BAB_KSA: { name: 'Bank Al Bilad', icon: BAB_KSA },
  NBI_IRQ: { name: 'National Bank of Iraq', icon: NBI_KUR },
  STR_AUS: { name: 'Stripe AU', icon: STRIPE },
  GIB_UAE: { name: 'Gulf International Bank', icon: GIB_SVG },
  Wise_DEU: { name: 'Wise, Germany', icon: DEFAULT_BANK },
  DBS_SG: { name: 'DBS SINGAPORE', icon: DEFAULT_BANK },
  RBI_SRB: { name: 'Raiffeisen Bank International', icon: RAIFFEISEN },
  MASHREQ_EGY: { name: 'MASHREQ', icon: MASHREQ_SVG },
  JPMC_NZL: { name: 'JPMorgan Chase Bank, NA New Zealand', icon: CHASE_SVG },
  ARB_SA: { name: 'Al Rajhi Bank', icon: ARB_SA },
  BB_LBN: { name: 'Blom Bank', icon: BLOOM_BANK },
  BOB_IRQ: { name: 'Bank of Baghdad', icon: BOB_IRQ },
  JPMC_PRI: { name: 'JPMorgan Chase Bank, N.A. (SW)', icon: CHASE_SVG },
  MASHREQ_UAE: { name: 'COMMUNITY FEDERAL SAVINGS BANK', icon: DEFAULT_BANK },
  JSB_PAK: { name: 'JS Bank', icon: JSB_PAK },
  STR_CAN: { name: 'Stripe', icon: STRIPE },
  MONOOVA_AU: { name: 'Cuscal Limited', icon: DEFAULT_BANK },
  JPMC_GBR: { name: 'JPMorgan Chase UK', icon: CHASE_SVG },
  STR_NZL: { name: 'Stripe NZ', icon: CHASE_SVG },
  CITI_SG: { name: 'Citibank Singapore', icon: CITI_BANK },
  TSC_USA: { name: 'Tri State Capital', icon: TRISTATE },
  IB_UZB: { name: 'Ipoteka bank', icon: DEFAULT_BANK },
  LB_ISL: { name: 'Lbank', icon: DEFAULT_BANK },
  BOP_PSE: { name: 'Bank of Palestine', icon: BOP_PSE },
  HIGHFI: { name: 'Barclays', icon: BARCLAYS },
  JPMC_PR: { name: 'DDT PR - AR (2072)', icon: CHASE_SVG },
  BL_ISR: { name: 'Bank Leumi', icon: DEFAULT_BANK },
  CB_IND: { name: 'CITI Bank', icon: CITI_BANK },
  NBI_KUR: { name: 'National Bank of Iraq', icon: NBI_KUR },
  QNB_QAT: { name: 'Qatar National Bank (QNB)', icon: QNB_QAT },
  MERCURY: { name: 'Mercury', icon: MERCURY },
  BOA_USA: { name: 'Copilot BOA', icon: BOB_IRQ },
  DB_DNK: { name: 'Danske Bank DNK', icon: DANSKE },
  BOL_LT: { name: 'UAB NIUM EU', icon: DEFAULT_BANK },
  JMPC_CA: { name: 'JPMorgan Chase Toronto', icon: CHASE_SVG },
  BOG_GEO: { name: 'Bank of Georgia', icon: DEFAULT_BANK },
  HSBC_AE: { name: 'HSBC BANK MIDDLE EAST LIMITED', icon: HSBC_SVG },
  DB_SWE: { name: 'Danske Bank SWE', icon: DANSKE },
  ANB_SA: { name: 'Arab National Bank', icon: ARB_SA },
  NBE_EG: { name: 'National Bank of Egypt, Egypt', icon: DEFAULT_BANK },
  CFSB_USINTL: { name: 'COMMUNITY FEDERAL SAVINGS BANK', icon: DEFAULT_BANK },
  Vietcombank_VNM: { name: 'Vietcombank, Vietnam', icon: DEFAULT_BANK },
  UC_DEU: { name: 'UniCredit DEU', icon: UNICREDIT },
  CFSB_US: { name: 'COMMUNITY FEDERAL SAVINGS BANK', icon: DEFAULT_BANK },
  NBK_KWT: { name: 'National Bank of Kuwait, Kuwait', icon: NBK_KWT },
  HSBC_SG: { name: 'HSBC Singapore', icon: HSBC_SVG },
  MASHREQ_NEO_SME_UAE: { name: 'Mashreq NEOBiz', icon: MASHREQ_SVG },
  BOH: { name: 'Bank of Hawaii', icon: DEFAULT_BANK },
  DBS_HK: { name: 'DBS HONGKONG', icon: DEFAULT_BANK },
  JPMC_KSA: { name: 'JP Morgan Chase Bank N.A. Riyadh Branch', icon: CHASE_SVG },
};

export enum PIVOT_DATA_EXPORT_FORMAT {
  CSV = 'csv',
  EXCEL = 'excel',
}
