// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock_store

import (
	context "context"

	models "github.com/Zampfi/application-platform/services/api/db/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockConnectionPoliciesStore is an autogenerated mock type for the ConnectionPoliciesStore type
type MockConnectionPoliciesStore struct {
	mock.Mock
}

type MockConnectionPoliciesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionPoliciesStore) EXPECT() *MockConnectionPoliciesStore_Expecter {
	return &MockConnectionPoliciesStore_Expecter{mock: &_m.Mock}
}

// CreateConnectionPolicy provides a mock function with given fields: ctx, connectionId, audienceType, audienceId, privilege
func (_m *MockConnectionPoliciesStore) CreateConnectionPolicy(ctx context.Context, connectionId uuid.UUID, audienceType models.AudienceType, audienceId uuid.UUID, privilege models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, connectionId, audienceType, audienceId, privilege)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnectionPolicy")
	}

	var r0 *models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, connectionId, audienceType, audienceId, privilege)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) *models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, connectionId, audienceType, audienceId, privilege)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) error); ok {
		r1 = rf(ctx, connectionId, audienceType, audienceId, privilege)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionPoliciesStore_CreateConnectionPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnectionPolicy'
type MockConnectionPoliciesStore_CreateConnectionPolicy_Call struct {
	*mock.Call
}

// CreateConnectionPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionId uuid.UUID
//   - audienceType models.AudienceType
//   - audienceId uuid.UUID
//   - privilege models.ResourcePrivilege
func (_e *MockConnectionPoliciesStore_Expecter) CreateConnectionPolicy(ctx interface{}, connectionId interface{}, audienceType interface{}, audienceId interface{}, privilege interface{}) *MockConnectionPoliciesStore_CreateConnectionPolicy_Call {
	return &MockConnectionPoliciesStore_CreateConnectionPolicy_Call{Call: _e.mock.On("CreateConnectionPolicy", ctx, connectionId, audienceType, audienceId, privilege)}
}

func (_c *MockConnectionPoliciesStore_CreateConnectionPolicy_Call) Run(run func(ctx context.Context, connectionId uuid.UUID, audienceType models.AudienceType, audienceId uuid.UUID, privilege models.ResourcePrivilege)) *MockConnectionPoliciesStore_CreateConnectionPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.AudienceType), args[3].(uuid.UUID), args[4].(models.ResourcePrivilege))
	})
	return _c
}

func (_c *MockConnectionPoliciesStore_CreateConnectionPolicy_Call) Return(_a0 *models.ResourceAudiencePolicy, _a1 error) *MockConnectionPoliciesStore_CreateConnectionPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionPoliciesStore_CreateConnectionPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)) *MockConnectionPoliciesStore_CreateConnectionPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionPolicies provides a mock function with given fields: ctx, connectionId
func (_m *MockConnectionPoliciesStore) GetConnectionPolicies(ctx context.Context, connectionId uuid.UUID) ([]models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, connectionId)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionPolicies")
	}

	var r0 []models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, connectionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, connectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, connectionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionPoliciesStore_GetConnectionPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionPolicies'
type MockConnectionPoliciesStore_GetConnectionPolicies_Call struct {
	*mock.Call
}

// GetConnectionPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionId uuid.UUID
func (_e *MockConnectionPoliciesStore_Expecter) GetConnectionPolicies(ctx interface{}, connectionId interface{}) *MockConnectionPoliciesStore_GetConnectionPolicies_Call {
	return &MockConnectionPoliciesStore_GetConnectionPolicies_Call{Call: _e.mock.On("GetConnectionPolicies", ctx, connectionId)}
}

func (_c *MockConnectionPoliciesStore_GetConnectionPolicies_Call) Run(run func(ctx context.Context, connectionId uuid.UUID)) *MockConnectionPoliciesStore_GetConnectionPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockConnectionPoliciesStore_GetConnectionPolicies_Call) Return(_a0 []models.ResourceAudiencePolicy, _a1 error) *MockConnectionPoliciesStore_GetConnectionPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionPoliciesStore_GetConnectionPolicies_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.ResourceAudiencePolicy, error)) *MockConnectionPoliciesStore_GetConnectionPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConnectionPolicy provides a mock function with given fields: ctx, connectionId, audienceId, privilege
func (_m *MockConnectionPoliciesStore) UpdateConnectionPolicy(ctx context.Context, connectionId uuid.UUID, audienceId uuid.UUID, privilege models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, connectionId, audienceId, privilege)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnectionPolicy")
	}

	var r0 *models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, connectionId, audienceId, privilege)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) *models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, connectionId, audienceId, privilege)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) error); ok {
		r1 = rf(ctx, connectionId, audienceId, privilege)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnectionPoliciesStore_UpdateConnectionPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConnectionPolicy'
type MockConnectionPoliciesStore_UpdateConnectionPolicy_Call struct {
	*mock.Call
}

// UpdateConnectionPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionId uuid.UUID
//   - audienceId uuid.UUID
//   - privilege models.ResourcePrivilege
func (_e *MockConnectionPoliciesStore_Expecter) UpdateConnectionPolicy(ctx interface{}, connectionId interface{}, audienceId interface{}, privilege interface{}) *MockConnectionPoliciesStore_UpdateConnectionPolicy_Call {
	return &MockConnectionPoliciesStore_UpdateConnectionPolicy_Call{Call: _e.mock.On("UpdateConnectionPolicy", ctx, connectionId, audienceId, privilege)}
}

func (_c *MockConnectionPoliciesStore_UpdateConnectionPolicy_Call) Run(run func(ctx context.Context, connectionId uuid.UUID, audienceId uuid.UUID, privilege models.ResourcePrivilege)) *MockConnectionPoliciesStore_UpdateConnectionPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(models.ResourcePrivilege))
	})
	return _c
}

func (_c *MockConnectionPoliciesStore_UpdateConnectionPolicy_Call) Return(_a0 *models.ResourceAudiencePolicy, _a1 error) *MockConnectionPoliciesStore_UpdateConnectionPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnectionPoliciesStore_UpdateConnectionPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)) *MockConnectionPoliciesStore_UpdateConnectionPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnectionPoliciesStore creates a new instance of MockConnectionPoliciesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionPoliciesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionPoliciesStore {
	mock := &MockConnectionPoliciesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
