// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock_store

import (
	context "context"
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Zampfi/application-platform/services/api/db/models"

	store "github.com/Zampfi/application-platform/services/api/db/store"

	uuid "github.com/google/uuid"
)

// MockOrganizationStore is an autogenerated mock type for the OrganizationStore type
type MockOrganizationStore struct {
	mock.Mock
}

type MockOrganizationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationStore) EXPECT() *MockOrganizationStore_Expecter {
	return &MockOrganizationStore_Expecter{mock: &_m.Mock}
}

// CreateOrganization provides a mock function with given fields: ctx, name, description, ownerId
func (_m *MockOrganizationStore) CreateOrganization(ctx context.Context, name string, description *string, ownerId uuid.UUID) (*models.Organization, error) {
	ret := _m.Called(ctx, name, description, ownerId)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, uuid.UUID) (*models.Organization, error)); ok {
		return rf(ctx, name, description, ownerId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, uuid.UUID) *models.Organization); ok {
		r0 = rf(ctx, name, description, ownerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, uuid.UUID) error); ok {
		r1 = rf(ctx, name, description, ownerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type MockOrganizationStore_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - ownerId uuid.UUID
func (_e *MockOrganizationStore_Expecter) CreateOrganization(ctx interface{}, name interface{}, description interface{}, ownerId interface{}) *MockOrganizationStore_CreateOrganization_Call {
	return &MockOrganizationStore_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", ctx, name, description, ownerId)}
}

func (_c *MockOrganizationStore_CreateOrganization_Call) Run(run func(ctx context.Context, name string, description *string, ownerId uuid.UUID)) *MockOrganizationStore_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_CreateOrganization_Call) Return(_a0 *models.Organization, _a1 error) *MockOrganizationStore_CreateOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_CreateOrganization_Call) RunAndReturn(run func(context.Context, string, *string, uuid.UUID) (*models.Organization, error)) *MockOrganizationStore_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganizationInvitation provides a mock function with given fields: ctx, organizationId, targetEmail, privilege
func (_m *MockOrganizationStore) CreateOrganizationInvitation(ctx context.Context, organizationId uuid.UUID, targetEmail string, privilege models.ResourcePrivilege) (*models.OrganizationInvitation, error) {
	ret := _m.Called(ctx, organizationId, targetEmail, privilege)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationInvitation")
	}

	var r0 *models.OrganizationInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, models.ResourcePrivilege) (*models.OrganizationInvitation, error)); ok {
		return rf(ctx, organizationId, targetEmail, privilege)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, models.ResourcePrivilege) *models.OrganizationInvitation); ok {
		r0 = rf(ctx, organizationId, targetEmail, privilege)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, models.ResourcePrivilege) error); ok {
		r1 = rf(ctx, organizationId, targetEmail, privilege)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_CreateOrganizationInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizationInvitation'
type MockOrganizationStore_CreateOrganizationInvitation_Call struct {
	*mock.Call
}

// CreateOrganizationInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
//   - targetEmail string
//   - privilege models.ResourcePrivilege
func (_e *MockOrganizationStore_Expecter) CreateOrganizationInvitation(ctx interface{}, organizationId interface{}, targetEmail interface{}, privilege interface{}) *MockOrganizationStore_CreateOrganizationInvitation_Call {
	return &MockOrganizationStore_CreateOrganizationInvitation_Call{Call: _e.mock.On("CreateOrganizationInvitation", ctx, organizationId, targetEmail, privilege)}
}

func (_c *MockOrganizationStore_CreateOrganizationInvitation_Call) Run(run func(ctx context.Context, organizationId uuid.UUID, targetEmail string, privilege models.ResourcePrivilege)) *MockOrganizationStore_CreateOrganizationInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(models.ResourcePrivilege))
	})
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationInvitation_Call) Return(_a0 *models.OrganizationInvitation, _a1 error) *MockOrganizationStore_CreateOrganizationInvitation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationInvitation_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, models.ResourcePrivilege) (*models.OrganizationInvitation, error)) *MockOrganizationStore_CreateOrganizationInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganizationInvitationStatus provides a mock function with given fields: ctx, invitationId, status
func (_m *MockOrganizationStore) CreateOrganizationInvitationStatus(ctx context.Context, invitationId uuid.UUID, status models.InvitationStatus) (*models.OrganizationInvitationStatus, error) {
	ret := _m.Called(ctx, invitationId, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationInvitationStatus")
	}

	var r0 *models.OrganizationInvitationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.InvitationStatus) (*models.OrganizationInvitationStatus, error)); ok {
		return rf(ctx, invitationId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.InvitationStatus) *models.OrganizationInvitationStatus); ok {
		r0 = rf(ctx, invitationId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationInvitationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.InvitationStatus) error); ok {
		r1 = rf(ctx, invitationId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_CreateOrganizationInvitationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizationInvitationStatus'
type MockOrganizationStore_CreateOrganizationInvitationStatus_Call struct {
	*mock.Call
}

// CreateOrganizationInvitationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - invitationId uuid.UUID
//   - status models.InvitationStatus
func (_e *MockOrganizationStore_Expecter) CreateOrganizationInvitationStatus(ctx interface{}, invitationId interface{}, status interface{}) *MockOrganizationStore_CreateOrganizationInvitationStatus_Call {
	return &MockOrganizationStore_CreateOrganizationInvitationStatus_Call{Call: _e.mock.On("CreateOrganizationInvitationStatus", ctx, invitationId, status)}
}

func (_c *MockOrganizationStore_CreateOrganizationInvitationStatus_Call) Run(run func(ctx context.Context, invitationId uuid.UUID, status models.InvitationStatus)) *MockOrganizationStore_CreateOrganizationInvitationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.InvitationStatus))
	})
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationInvitationStatus_Call) Return(_a0 *models.OrganizationInvitationStatus, _a1 error) *MockOrganizationStore_CreateOrganizationInvitationStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationInvitationStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.InvitationStatus) (*models.OrganizationInvitationStatus, error)) *MockOrganizationStore_CreateOrganizationInvitationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganizationMembershipRequest provides a mock function with given fields: ctx, organizationId, userId, status
func (_m *MockOrganizationStore) CreateOrganizationMembershipRequest(ctx context.Context, organizationId uuid.UUID, userId uuid.UUID, status models.OrgMembershipStatus) (*models.OrganizationMembershipRequest, error) {
	ret := _m.Called(ctx, organizationId, userId, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationMembershipRequest")
	}

	var r0 *models.OrganizationMembershipRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) (*models.OrganizationMembershipRequest, error)); ok {
		return rf(ctx, organizationId, userId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) *models.OrganizationMembershipRequest); ok {
		r0 = rf(ctx, organizationId, userId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationMembershipRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) error); ok {
		r1 = rf(ctx, organizationId, userId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_CreateOrganizationMembershipRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizationMembershipRequest'
type MockOrganizationStore_CreateOrganizationMembershipRequest_Call struct {
	*mock.Call
}

// CreateOrganizationMembershipRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
//   - userId uuid.UUID
//   - status models.OrgMembershipStatus
func (_e *MockOrganizationStore_Expecter) CreateOrganizationMembershipRequest(ctx interface{}, organizationId interface{}, userId interface{}, status interface{}) *MockOrganizationStore_CreateOrganizationMembershipRequest_Call {
	return &MockOrganizationStore_CreateOrganizationMembershipRequest_Call{Call: _e.mock.On("CreateOrganizationMembershipRequest", ctx, organizationId, userId, status)}
}

func (_c *MockOrganizationStore_CreateOrganizationMembershipRequest_Call) Run(run func(ctx context.Context, organizationId uuid.UUID, userId uuid.UUID, status models.OrgMembershipStatus)) *MockOrganizationStore_CreateOrganizationMembershipRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(models.OrgMembershipStatus))
	})
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationMembershipRequest_Call) Return(_a0 *models.OrganizationMembershipRequest, _a1 error) *MockOrganizationStore_CreateOrganizationMembershipRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationMembershipRequest_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) (*models.OrganizationMembershipRequest, error)) *MockOrganizationStore_CreateOrganizationMembershipRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganizationPolicy provides a mock function with given fields: ctx, orgId, audienceType, audienceId, privilege
func (_m *MockOrganizationStore) CreateOrganizationPolicy(ctx context.Context, orgId uuid.UUID, audienceType models.AudienceType, audienceId uuid.UUID, privilege models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, orgId, audienceType, audienceId, privilege)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizationPolicy")
	}

	var r0 *models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, orgId, audienceType, audienceId, privilege)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) *models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, orgId, audienceType, audienceId, privilege)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) error); ok {
		r1 = rf(ctx, orgId, audienceType, audienceId, privilege)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_CreateOrganizationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizationPolicy'
type MockOrganizationStore_CreateOrganizationPolicy_Call struct {
	*mock.Call
}

// CreateOrganizationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId uuid.UUID
//   - audienceType models.AudienceType
//   - audienceId uuid.UUID
//   - privilege models.ResourcePrivilege
func (_e *MockOrganizationStore_Expecter) CreateOrganizationPolicy(ctx interface{}, orgId interface{}, audienceType interface{}, audienceId interface{}, privilege interface{}) *MockOrganizationStore_CreateOrganizationPolicy_Call {
	return &MockOrganizationStore_CreateOrganizationPolicy_Call{Call: _e.mock.On("CreateOrganizationPolicy", ctx, orgId, audienceType, audienceId, privilege)}
}

func (_c *MockOrganizationStore_CreateOrganizationPolicy_Call) Run(run func(ctx context.Context, orgId uuid.UUID, audienceType models.AudienceType, audienceId uuid.UUID, privilege models.ResourcePrivilege)) *MockOrganizationStore_CreateOrganizationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.AudienceType), args[3].(uuid.UUID), args[4].(models.ResourcePrivilege))
	})
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationPolicy_Call) Return(_a0 *models.ResourceAudiencePolicy, _a1 error) *MockOrganizationStore_CreateOrganizationPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_CreateOrganizationPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.AudienceType, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)) *MockOrganizationStore_CreateOrganizationPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSSOConfig provides a mock function with given fields: ctx, organizationId, ssoProviderID, ssoProviderName, ssoConfig, emailDomain
func (_m *MockOrganizationStore) CreateSSOConfig(ctx context.Context, organizationId uuid.UUID, ssoProviderID string, ssoProviderName string, ssoConfig json.RawMessage, emailDomain string) (*models.OrganizationSSOConfig, error) {
	ret := _m.Called(ctx, organizationId, ssoProviderID, ssoProviderName, ssoConfig, emailDomain)

	if len(ret) == 0 {
		panic("no return value specified for CreateSSOConfig")
	}

	var r0 *models.OrganizationSSOConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, json.RawMessage, string) (*models.OrganizationSSOConfig, error)); ok {
		return rf(ctx, organizationId, ssoProviderID, ssoProviderName, ssoConfig, emailDomain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, json.RawMessage, string) *models.OrganizationSSOConfig); ok {
		r0 = rf(ctx, organizationId, ssoProviderID, ssoProviderName, ssoConfig, emailDomain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationSSOConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, json.RawMessage, string) error); ok {
		r1 = rf(ctx, organizationId, ssoProviderID, ssoProviderName, ssoConfig, emailDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_CreateSSOConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSSOConfig'
type MockOrganizationStore_CreateSSOConfig_Call struct {
	*mock.Call
}

// CreateSSOConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
//   - ssoProviderID string
//   - ssoProviderName string
//   - ssoConfig json.RawMessage
//   - emailDomain string
func (_e *MockOrganizationStore_Expecter) CreateSSOConfig(ctx interface{}, organizationId interface{}, ssoProviderID interface{}, ssoProviderName interface{}, ssoConfig interface{}, emailDomain interface{}) *MockOrganizationStore_CreateSSOConfig_Call {
	return &MockOrganizationStore_CreateSSOConfig_Call{Call: _e.mock.On("CreateSSOConfig", ctx, organizationId, ssoProviderID, ssoProviderName, ssoConfig, emailDomain)}
}

func (_c *MockOrganizationStore_CreateSSOConfig_Call) Run(run func(ctx context.Context, organizationId uuid.UUID, ssoProviderID string, ssoProviderName string, ssoConfig json.RawMessage, emailDomain string)) *MockOrganizationStore_CreateSSOConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(json.RawMessage), args[5].(string))
	})
	return _c
}

func (_c *MockOrganizationStore_CreateSSOConfig_Call) Return(_a0 *models.OrganizationSSOConfig, _a1 error) *MockOrganizationStore_CreateSSOConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_CreateSSOConfig_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, json.RawMessage, string) (*models.OrganizationSSOConfig, error)) *MockOrganizationStore_CreateSSOConfig_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganizationPolicy provides a mock function with given fields: ctx, orgId, audienceId
func (_m *MockOrganizationStore) DeleteOrganizationPolicy(ctx context.Context, orgId uuid.UUID, audienceId uuid.UUID) error {
	ret := _m.Called(ctx, orgId, audienceId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizationPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, orgId, audienceId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationStore_DeleteOrganizationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganizationPolicy'
type MockOrganizationStore_DeleteOrganizationPolicy_Call struct {
	*mock.Call
}

// DeleteOrganizationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId uuid.UUID
//   - audienceId uuid.UUID
func (_e *MockOrganizationStore_Expecter) DeleteOrganizationPolicy(ctx interface{}, orgId interface{}, audienceId interface{}) *MockOrganizationStore_DeleteOrganizationPolicy_Call {
	return &MockOrganizationStore_DeleteOrganizationPolicy_Call{Call: _e.mock.On("DeleteOrganizationPolicy", ctx, orgId, audienceId)}
}

func (_c *MockOrganizationStore_DeleteOrganizationPolicy_Call) Run(run func(ctx context.Context, orgId uuid.UUID, audienceId uuid.UUID)) *MockOrganizationStore_DeleteOrganizationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_DeleteOrganizationPolicy_Call) Return(_a0 error) *MockOrganizationStore_DeleteOrganizationPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationStore_DeleteOrganizationPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockOrganizationStore_DeleteOrganizationPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationById provides a mock function with given fields: ctx, organizationId
func (_m *MockOrganizationStore) GetOrganizationById(ctx context.Context, organizationId string) (*models.Organization, error) {
	ret := _m.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationById")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Organization, error)); ok {
		return rf(ctx, organizationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Organization); ok {
		r0 = rf(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationById'
type MockOrganizationStore_GetOrganizationById_Call struct {
	*mock.Call
}

// GetOrganizationById is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId string
func (_e *MockOrganizationStore_Expecter) GetOrganizationById(ctx interface{}, organizationId interface{}) *MockOrganizationStore_GetOrganizationById_Call {
	return &MockOrganizationStore_GetOrganizationById_Call{Call: _e.mock.On("GetOrganizationById", ctx, organizationId)}
}

func (_c *MockOrganizationStore_GetOrganizationById_Call) Run(run func(ctx context.Context, organizationId string)) *MockOrganizationStore_GetOrganizationById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationById_Call) Return(_a0 *models.Organization, _a1 error) *MockOrganizationStore_GetOrganizationById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationById_Call) RunAndReturn(run func(context.Context, string) (*models.Organization, error)) *MockOrganizationStore_GetOrganizationById_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationInvitationById provides a mock function with given fields: ctx, invitationId
func (_m *MockOrganizationStore) GetOrganizationInvitationById(ctx context.Context, invitationId uuid.UUID) (*models.OrganizationInvitation, error) {
	ret := _m.Called(ctx, invitationId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationInvitationById")
	}

	var r0 *models.OrganizationInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.OrganizationInvitation, error)); ok {
		return rf(ctx, invitationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.OrganizationInvitation); ok {
		r0 = rf(ctx, invitationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, invitationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationInvitationById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationInvitationById'
type MockOrganizationStore_GetOrganizationInvitationById_Call struct {
	*mock.Call
}

// GetOrganizationInvitationById is a helper method to define mock.On call
//   - ctx context.Context
//   - invitationId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationInvitationById(ctx interface{}, invitationId interface{}) *MockOrganizationStore_GetOrganizationInvitationById_Call {
	return &MockOrganizationStore_GetOrganizationInvitationById_Call{Call: _e.mock.On("GetOrganizationInvitationById", ctx, invitationId)}
}

func (_c *MockOrganizationStore_GetOrganizationInvitationById_Call) Run(run func(ctx context.Context, invitationId uuid.UUID)) *MockOrganizationStore_GetOrganizationInvitationById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationById_Call) Return(_a0 *models.OrganizationInvitation, _a1 error) *MockOrganizationStore_GetOrganizationInvitationById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationById_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.OrganizationInvitation, error)) *MockOrganizationStore_GetOrganizationInvitationById_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationInvitationsAll provides a mock function with given fields: ctx
func (_m *MockOrganizationStore) GetOrganizationInvitationsAll(ctx context.Context) ([]models.OrganizationInvitation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationInvitationsAll")
	}

	var r0 []models.OrganizationInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.OrganizationInvitation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.OrganizationInvitation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrganizationInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationInvitationsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationInvitationsAll'
type MockOrganizationStore_GetOrganizationInvitationsAll_Call struct {
	*mock.Call
}

// GetOrganizationInvitationsAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrganizationStore_Expecter) GetOrganizationInvitationsAll(ctx interface{}) *MockOrganizationStore_GetOrganizationInvitationsAll_Call {
	return &MockOrganizationStore_GetOrganizationInvitationsAll_Call{Call: _e.mock.On("GetOrganizationInvitationsAll", ctx)}
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsAll_Call) Run(run func(ctx context.Context)) *MockOrganizationStore_GetOrganizationInvitationsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsAll_Call) Return(_a0 []models.OrganizationInvitation, _a1 error) *MockOrganizationStore_GetOrganizationInvitationsAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsAll_Call) RunAndReturn(run func(context.Context) ([]models.OrganizationInvitation, error)) *MockOrganizationStore_GetOrganizationInvitationsAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationInvitationsAndMembershipRequests provides a mock function with given fields: ctx, organizationId
func (_m *MockOrganizationStore) GetOrganizationInvitationsAndMembershipRequests(ctx context.Context, organizationId uuid.UUID) (*models.Organization, error) {
	ret := _m.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationInvitationsAndMembershipRequests")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Organization, error)); ok {
		return rf(ctx, organizationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Organization); ok {
		r0 = rf(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationInvitationsAndMembershipRequests'
type MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call struct {
	*mock.Call
}

// GetOrganizationInvitationsAndMembershipRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationInvitationsAndMembershipRequests(ctx interface{}, organizationId interface{}) *MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call {
	return &MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call{Call: _e.mock.On("GetOrganizationInvitationsAndMembershipRequests", ctx, organizationId)}
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call) Run(run func(ctx context.Context, organizationId uuid.UUID)) *MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call) Return(_a0 *models.Organization, _a1 error) *MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Organization, error)) *MockOrganizationStore_GetOrganizationInvitationsAndMembershipRequests_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationInvitationsByOrganizationId provides a mock function with given fields: ctx, organizationId
func (_m *MockOrganizationStore) GetOrganizationInvitationsByOrganizationId(ctx context.Context, organizationId uuid.UUID) ([]models.OrganizationInvitation, error) {
	ret := _m.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationInvitationsByOrganizationId")
	}

	var r0 []models.OrganizationInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.OrganizationInvitation, error)); ok {
		return rf(ctx, organizationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.OrganizationInvitation); ok {
		r0 = rf(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrganizationInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationInvitationsByOrganizationId'
type MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call struct {
	*mock.Call
}

// GetOrganizationInvitationsByOrganizationId is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationInvitationsByOrganizationId(ctx interface{}, organizationId interface{}) *MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call {
	return &MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call{Call: _e.mock.On("GetOrganizationInvitationsByOrganizationId", ctx, organizationId)}
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call) Run(run func(ctx context.Context, organizationId uuid.UUID)) *MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call) Return(_a0 []models.OrganizationInvitation, _a1 error) *MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.OrganizationInvitation, error)) *MockOrganizationStore_GetOrganizationInvitationsByOrganizationId_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationMembershipRequestsAll provides a mock function with given fields: ctx
func (_m *MockOrganizationStore) GetOrganizationMembershipRequestsAll(ctx context.Context) ([]models.OrganizationMembershipRequest, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationMembershipRequestsAll")
	}

	var r0 []models.OrganizationMembershipRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.OrganizationMembershipRequest, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.OrganizationMembershipRequest); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrganizationMembershipRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationMembershipRequestsAll'
type MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call struct {
	*mock.Call
}

// GetOrganizationMembershipRequestsAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrganizationStore_Expecter) GetOrganizationMembershipRequestsAll(ctx interface{}) *MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call {
	return &MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call{Call: _e.mock.On("GetOrganizationMembershipRequestsAll", ctx)}
}

func (_c *MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call) Run(run func(ctx context.Context)) *MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call) Return(_a0 []models.OrganizationMembershipRequest, _a1 error) *MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call) RunAndReturn(run func(context.Context) ([]models.OrganizationMembershipRequest, error)) *MockOrganizationStore_GetOrganizationMembershipRequestsAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationMembershipRequestsByOrganizationId provides a mock function with given fields: ctx, organizationId
func (_m *MockOrganizationStore) GetOrganizationMembershipRequestsByOrganizationId(ctx context.Context, organizationId uuid.UUID) ([]models.OrganizationMembershipRequest, error) {
	ret := _m.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationMembershipRequestsByOrganizationId")
	}

	var r0 []models.OrganizationMembershipRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.OrganizationMembershipRequest, error)); ok {
		return rf(ctx, organizationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.OrganizationMembershipRequest); ok {
		r0 = rf(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrganizationMembershipRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationMembershipRequestsByOrganizationId'
type MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call struct {
	*mock.Call
}

// GetOrganizationMembershipRequestsByOrganizationId is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationMembershipRequestsByOrganizationId(ctx interface{}, organizationId interface{}) *MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call {
	return &MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call{Call: _e.mock.On("GetOrganizationMembershipRequestsByOrganizationId", ctx, organizationId)}
}

func (_c *MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call) Run(run func(ctx context.Context, organizationId uuid.UUID)) *MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call) Return(_a0 []models.OrganizationMembershipRequest, _a1 error) *MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.OrganizationMembershipRequest, error)) *MockOrganizationStore_GetOrganizationMembershipRequestsByOrganizationId_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationPolicies provides a mock function with given fields: ctx, orgId
func (_m *MockOrganizationStore) GetOrganizationPolicies(ctx context.Context, orgId uuid.UUID) ([]models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, orgId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationPolicies")
	}

	var r0 []models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, orgId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, orgId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationPolicies'
type MockOrganizationStore_GetOrganizationPolicies_Call struct {
	*mock.Call
}

// GetOrganizationPolicies is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationPolicies(ctx interface{}, orgId interface{}) *MockOrganizationStore_GetOrganizationPolicies_Call {
	return &MockOrganizationStore_GetOrganizationPolicies_Call{Call: _e.mock.On("GetOrganizationPolicies", ctx, orgId)}
}

func (_c *MockOrganizationStore_GetOrganizationPolicies_Call) Run(run func(ctx context.Context, orgId uuid.UUID)) *MockOrganizationStore_GetOrganizationPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationPolicies_Call) Return(_a0 []models.ResourceAudiencePolicy, _a1 error) *MockOrganizationStore_GetOrganizationPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationPolicies_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.ResourceAudiencePolicy, error)) *MockOrganizationStore_GetOrganizationPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationPoliciesByEmail provides a mock function with given fields: ctx, organizationId, email
func (_m *MockOrganizationStore) GetOrganizationPoliciesByEmail(ctx context.Context, organizationId uuid.UUID, email string) ([]models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, organizationId, email)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationPoliciesByEmail")
	}

	var r0 []models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, organizationId, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, organizationId, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, organizationId, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationPoliciesByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationPoliciesByEmail'
type MockOrganizationStore_GetOrganizationPoliciesByEmail_Call struct {
	*mock.Call
}

// GetOrganizationPoliciesByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
//   - email string
func (_e *MockOrganizationStore_Expecter) GetOrganizationPoliciesByEmail(ctx interface{}, organizationId interface{}, email interface{}) *MockOrganizationStore_GetOrganizationPoliciesByEmail_Call {
	return &MockOrganizationStore_GetOrganizationPoliciesByEmail_Call{Call: _e.mock.On("GetOrganizationPoliciesByEmail", ctx, organizationId, email)}
}

func (_c *MockOrganizationStore_GetOrganizationPoliciesByEmail_Call) Run(run func(ctx context.Context, organizationId uuid.UUID, email string)) *MockOrganizationStore_GetOrganizationPoliciesByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationPoliciesByEmail_Call) Return(_a0 []models.ResourceAudiencePolicy, _a1 error) *MockOrganizationStore_GetOrganizationPoliciesByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationPoliciesByEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]models.ResourceAudiencePolicy, error)) *MockOrganizationStore_GetOrganizationPoliciesByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationPolicyByUser provides a mock function with given fields: ctx, organizationId, userId
func (_m *MockOrganizationStore) GetOrganizationPolicyByUser(ctx context.Context, organizationId uuid.UUID, userId uuid.UUID) (*models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, organizationId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationPolicyByUser")
	}

	var r0 *models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, organizationId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, organizationId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationPolicyByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationPolicyByUser'
type MockOrganizationStore_GetOrganizationPolicyByUser_Call struct {
	*mock.Call
}

// GetOrganizationPolicyByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
//   - userId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationPolicyByUser(ctx interface{}, organizationId interface{}, userId interface{}) *MockOrganizationStore_GetOrganizationPolicyByUser_Call {
	return &MockOrganizationStore_GetOrganizationPolicyByUser_Call{Call: _e.mock.On("GetOrganizationPolicyByUser", ctx, organizationId, userId)}
}

func (_c *MockOrganizationStore_GetOrganizationPolicyByUser_Call) Run(run func(ctx context.Context, organizationId uuid.UUID, userId uuid.UUID)) *MockOrganizationStore_GetOrganizationPolicyByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationPolicyByUser_Call) Return(_a0 *models.ResourceAudiencePolicy, _a1 error) *MockOrganizationStore_GetOrganizationPolicyByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationPolicyByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.ResourceAudiencePolicy, error)) *MockOrganizationStore_GetOrganizationPolicyByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationSSOConfigsByOrganizationId provides a mock function with given fields: ctx, organizationId
func (_m *MockOrganizationStore) GetOrganizationSSOConfigsByOrganizationId(ctx context.Context, organizationId uuid.UUID) ([]models.OrganizationSSOConfig, error) {
	ret := _m.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationSSOConfigsByOrganizationId")
	}

	var r0 []models.OrganizationSSOConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.OrganizationSSOConfig, error)); ok {
		return rf(ctx, organizationId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.OrganizationSSOConfig); ok {
		r0 = rf(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrganizationSSOConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationSSOConfigsByOrganizationId'
type MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call struct {
	*mock.Call
}

// GetOrganizationSSOConfigsByOrganizationId is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationSSOConfigsByOrganizationId(ctx interface{}, organizationId interface{}) *MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call {
	return &MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call{Call: _e.mock.On("GetOrganizationSSOConfigsByOrganizationId", ctx, organizationId)}
}

func (_c *MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call) Run(run func(ctx context.Context, organizationId uuid.UUID)) *MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call) Return(_a0 []models.OrganizationSSOConfig, _a1 error) *MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.OrganizationSSOConfig, error)) *MockOrganizationStore_GetOrganizationSSOConfigsByOrganizationId_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationsAll provides a mock function with given fields: ctx
func (_m *MockOrganizationStore) GetOrganizationsAll(ctx context.Context) ([]models.Organization, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationsAll")
	}

	var r0 []models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Organization, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Organization); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationsAll'
type MockOrganizationStore_GetOrganizationsAll_Call struct {
	*mock.Call
}

// GetOrganizationsAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrganizationStore_Expecter) GetOrganizationsAll(ctx interface{}) *MockOrganizationStore_GetOrganizationsAll_Call {
	return &MockOrganizationStore_GetOrganizationsAll_Call{Call: _e.mock.On("GetOrganizationsAll", ctx)}
}

func (_c *MockOrganizationStore_GetOrganizationsAll_Call) Run(run func(ctx context.Context)) *MockOrganizationStore_GetOrganizationsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationsAll_Call) Return(_a0 []models.Organization, _a1 error) *MockOrganizationStore_GetOrganizationsAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationsAll_Call) RunAndReturn(run func(context.Context) ([]models.Organization, error)) *MockOrganizationStore_GetOrganizationsAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationsByMemberId provides a mock function with given fields: ctx, memberId
func (_m *MockOrganizationStore) GetOrganizationsByMemberId(ctx context.Context, memberId uuid.UUID) ([]models.Organization, error) {
	ret := _m.Called(ctx, memberId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationsByMemberId")
	}

	var r0 []models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Organization, error)); ok {
		return rf(ctx, memberId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Organization); ok {
		r0 = rf(ctx, memberId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, memberId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetOrganizationsByMemberId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationsByMemberId'
type MockOrganizationStore_GetOrganizationsByMemberId_Call struct {
	*mock.Call
}

// GetOrganizationsByMemberId is a helper method to define mock.On call
//   - ctx context.Context
//   - memberId uuid.UUID
func (_e *MockOrganizationStore_Expecter) GetOrganizationsByMemberId(ctx interface{}, memberId interface{}) *MockOrganizationStore_GetOrganizationsByMemberId_Call {
	return &MockOrganizationStore_GetOrganizationsByMemberId_Call{Call: _e.mock.On("GetOrganizationsByMemberId", ctx, memberId)}
}

func (_c *MockOrganizationStore_GetOrganizationsByMemberId_Call) Run(run func(ctx context.Context, memberId uuid.UUID)) *MockOrganizationStore_GetOrganizationsByMemberId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationsByMemberId_Call) Return(_a0 []models.Organization, _a1 error) *MockOrganizationStore_GetOrganizationsByMemberId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetOrganizationsByMemberId_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Organization, error)) *MockOrganizationStore_GetOrganizationsByMemberId_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrimarySSOConfigByDomain provides a mock function with given fields: ctx, domain
func (_m *MockOrganizationStore) GetPrimarySSOConfigByDomain(ctx context.Context, domain string) (*models.OrganizationSSOConfig, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetPrimarySSOConfigByDomain")
	}

	var r0 *models.OrganizationSSOConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.OrganizationSSOConfig, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.OrganizationSSOConfig); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationSSOConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetPrimarySSOConfigByDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrimarySSOConfigByDomain'
type MockOrganizationStore_GetPrimarySSOConfigByDomain_Call struct {
	*mock.Call
}

// GetPrimarySSOConfigByDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockOrganizationStore_Expecter) GetPrimarySSOConfigByDomain(ctx interface{}, domain interface{}) *MockOrganizationStore_GetPrimarySSOConfigByDomain_Call {
	return &MockOrganizationStore_GetPrimarySSOConfigByDomain_Call{Call: _e.mock.On("GetPrimarySSOConfigByDomain", ctx, domain)}
}

func (_c *MockOrganizationStore_GetPrimarySSOConfigByDomain_Call) Run(run func(ctx context.Context, domain string)) *MockOrganizationStore_GetPrimarySSOConfigByDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationStore_GetPrimarySSOConfigByDomain_Call) Return(_a0 *models.OrganizationSSOConfig, _a1 error) *MockOrganizationStore_GetPrimarySSOConfigByDomain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetPrimarySSOConfigByDomain_Call) RunAndReturn(run func(context.Context, string) (*models.OrganizationSSOConfig, error)) *MockOrganizationStore_GetPrimarySSOConfigByDomain_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSOConfigByDomain provides a mock function with given fields: ctx, domain
func (_m *MockOrganizationStore) GetSSOConfigByDomain(ctx context.Context, domain string) (*models.OrganizationSSOConfig, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetSSOConfigByDomain")
	}

	var r0 *models.OrganizationSSOConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.OrganizationSSOConfig, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.OrganizationSSOConfig); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationSSOConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_GetSSOConfigByDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSOConfigByDomain'
type MockOrganizationStore_GetSSOConfigByDomain_Call struct {
	*mock.Call
}

// GetSSOConfigByDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockOrganizationStore_Expecter) GetSSOConfigByDomain(ctx interface{}, domain interface{}) *MockOrganizationStore_GetSSOConfigByDomain_Call {
	return &MockOrganizationStore_GetSSOConfigByDomain_Call{Call: _e.mock.On("GetSSOConfigByDomain", ctx, domain)}
}

func (_c *MockOrganizationStore_GetSSOConfigByDomain_Call) Run(run func(ctx context.Context, domain string)) *MockOrganizationStore_GetSSOConfigByDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationStore_GetSSOConfigByDomain_Call) Return(_a0 *models.OrganizationSSOConfig, _a1 error) *MockOrganizationStore_GetSSOConfigByDomain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_GetSSOConfigByDomain_Call) RunAndReturn(run func(context.Context, string) (*models.OrganizationSSOConfig, error)) *MockOrganizationStore_GetSSOConfigByDomain_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganizationInvitationStatus provides a mock function with given fields: ctx, invitationId, status
func (_m *MockOrganizationStore) UpdateOrganizationInvitationStatus(ctx context.Context, invitationId uuid.UUID, status models.InvitationStatus) (*models.OrganizationInvitationStatus, error) {
	ret := _m.Called(ctx, invitationId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationInvitationStatus")
	}

	var r0 *models.OrganizationInvitationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.InvitationStatus) (*models.OrganizationInvitationStatus, error)); ok {
		return rf(ctx, invitationId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.InvitationStatus) *models.OrganizationInvitationStatus); ok {
		r0 = rf(ctx, invitationId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationInvitationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.InvitationStatus) error); ok {
		r1 = rf(ctx, invitationId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_UpdateOrganizationInvitationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganizationInvitationStatus'
type MockOrganizationStore_UpdateOrganizationInvitationStatus_Call struct {
	*mock.Call
}

// UpdateOrganizationInvitationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - invitationId uuid.UUID
//   - status models.InvitationStatus
func (_e *MockOrganizationStore_Expecter) UpdateOrganizationInvitationStatus(ctx interface{}, invitationId interface{}, status interface{}) *MockOrganizationStore_UpdateOrganizationInvitationStatus_Call {
	return &MockOrganizationStore_UpdateOrganizationInvitationStatus_Call{Call: _e.mock.On("UpdateOrganizationInvitationStatus", ctx, invitationId, status)}
}

func (_c *MockOrganizationStore_UpdateOrganizationInvitationStatus_Call) Run(run func(ctx context.Context, invitationId uuid.UUID, status models.InvitationStatus)) *MockOrganizationStore_UpdateOrganizationInvitationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.InvitationStatus))
	})
	return _c
}

func (_c *MockOrganizationStore_UpdateOrganizationInvitationStatus_Call) Return(_a0 *models.OrganizationInvitationStatus, _a1 error) *MockOrganizationStore_UpdateOrganizationInvitationStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_UpdateOrganizationInvitationStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.InvitationStatus) (*models.OrganizationInvitationStatus, error)) *MockOrganizationStore_UpdateOrganizationInvitationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganizationPolicy provides a mock function with given fields: ctx, orgId, audienceId, privilege
func (_m *MockOrganizationStore) UpdateOrganizationPolicy(ctx context.Context, orgId uuid.UUID, audienceId uuid.UUID, privilege models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error) {
	ret := _m.Called(ctx, orgId, audienceId, privilege)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationPolicy")
	}

	var r0 *models.ResourceAudiencePolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)); ok {
		return rf(ctx, orgId, audienceId, privilege)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) *models.ResourceAudiencePolicy); ok {
		r0 = rf(ctx, orgId, audienceId, privilege)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceAudiencePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) error); ok {
		r1 = rf(ctx, orgId, audienceId, privilege)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_UpdateOrganizationPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganizationPolicy'
type MockOrganizationStore_UpdateOrganizationPolicy_Call struct {
	*mock.Call
}

// UpdateOrganizationPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId uuid.UUID
//   - audienceId uuid.UUID
//   - privilege models.ResourcePrivilege
func (_e *MockOrganizationStore_Expecter) UpdateOrganizationPolicy(ctx interface{}, orgId interface{}, audienceId interface{}, privilege interface{}) *MockOrganizationStore_UpdateOrganizationPolicy_Call {
	return &MockOrganizationStore_UpdateOrganizationPolicy_Call{Call: _e.mock.On("UpdateOrganizationPolicy", ctx, orgId, audienceId, privilege)}
}

func (_c *MockOrganizationStore_UpdateOrganizationPolicy_Call) Run(run func(ctx context.Context, orgId uuid.UUID, audienceId uuid.UUID, privilege models.ResourcePrivilege)) *MockOrganizationStore_UpdateOrganizationPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(models.ResourcePrivilege))
	})
	return _c
}

func (_c *MockOrganizationStore_UpdateOrganizationPolicy_Call) Return(_a0 *models.ResourceAudiencePolicy, _a1 error) *MockOrganizationStore_UpdateOrganizationPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_UpdateOrganizationPolicy_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, models.ResourcePrivilege) (*models.ResourceAudiencePolicy, error)) *MockOrganizationStore_UpdateOrganizationPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePendingOrganizationMembershipRequest provides a mock function with given fields: ctx, organizationId, userId, status
func (_m *MockOrganizationStore) UpdatePendingOrganizationMembershipRequest(ctx context.Context, organizationId uuid.UUID, userId uuid.UUID, status models.OrgMembershipStatus) (*models.OrganizationMembershipRequest, error) {
	ret := _m.Called(ctx, organizationId, userId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePendingOrganizationMembershipRequest")
	}

	var r0 *models.OrganizationMembershipRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) (*models.OrganizationMembershipRequest, error)); ok {
		return rf(ctx, organizationId, userId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) *models.OrganizationMembershipRequest); ok {
		r0 = rf(ctx, organizationId, userId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OrganizationMembershipRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) error); ok {
		r1 = rf(ctx, organizationId, userId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePendingOrganizationMembershipRequest'
type MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call struct {
	*mock.Call
}

// UpdatePendingOrganizationMembershipRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
//   - userId uuid.UUID
//   - status models.OrgMembershipStatus
func (_e *MockOrganizationStore_Expecter) UpdatePendingOrganizationMembershipRequest(ctx interface{}, organizationId interface{}, userId interface{}, status interface{}) *MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call {
	return &MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call{Call: _e.mock.On("UpdatePendingOrganizationMembershipRequest", ctx, organizationId, userId, status)}
}

func (_c *MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call) Run(run func(ctx context.Context, organizationId uuid.UUID, userId uuid.UUID, status models.OrgMembershipStatus)) *MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(models.OrgMembershipStatus))
	})
	return _c
}

func (_c *MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call) Return(_a0 *models.OrganizationMembershipRequest, _a1 error) *MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, models.OrgMembershipStatus) (*models.OrganizationMembershipRequest, error)) *MockOrganizationStore_UpdatePendingOrganizationMembershipRequest_Call {
	_c.Call.Return(run)
	return _c
}

// WithOrganizationTransaction provides a mock function with given fields: ctx, fn
func (_m *MockOrganizationStore) WithOrganizationTransaction(ctx context.Context, fn func(store.OrganizationStore) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithOrganizationTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(store.OrganizationStore) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationStore_WithOrganizationTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithOrganizationTransaction'
type MockOrganizationStore_WithOrganizationTransaction_Call struct {
	*mock.Call
}

// WithOrganizationTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(store.OrganizationStore) error
func (_e *MockOrganizationStore_Expecter) WithOrganizationTransaction(ctx interface{}, fn interface{}) *MockOrganizationStore_WithOrganizationTransaction_Call {
	return &MockOrganizationStore_WithOrganizationTransaction_Call{Call: _e.mock.On("WithOrganizationTransaction", ctx, fn)}
}

func (_c *MockOrganizationStore_WithOrganizationTransaction_Call) Run(run func(ctx context.Context, fn func(store.OrganizationStore) error)) *MockOrganizationStore_WithOrganizationTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(store.OrganizationStore) error))
	})
	return _c
}

func (_c *MockOrganizationStore_WithOrganizationTransaction_Call) Return(_a0 error) *MockOrganizationStore_WithOrganizationTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationStore_WithOrganizationTransaction_Call) RunAndReturn(run func(context.Context, func(store.OrganizationStore) error) error) *MockOrganizationStore_WithOrganizationTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationStore creates a new instance of MockOrganizationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationStore {
	mock := &MockOrganizationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
