// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock_rosetta

import (
	context "context"

	constants "github.com/Zampfi/application-platform/services/api/pkg/dataplatform/constants"

	mock "github.com/stretchr/testify/mock"
)

// MockRosettaService is an autogenerated mock type for the RosettaService type
type MockRosettaService struct {
	mock.Mock
}

type MockRosettaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRosettaService) EXPECT() *MockRosettaService_Expecter {
	return &MockRosettaService_Expecter{mock: &_m.Mock}
}

// TranslateQuery provides a mock function with given fields: ctx, query, providerType
func (_m *MockRosettaService) TranslateQuery(ctx context.Context, query string, providerType constants.ProviderType) (string, error) {
	ret := _m.Called(ctx, query, providerType)

	if len(ret) == 0 {
		panic("no return value specified for TranslateQuery")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.ProviderType) (string, error)); ok {
		return rf(ctx, query, providerType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, constants.ProviderType) string); ok {
		r0 = rf(ctx, query, providerType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, constants.ProviderType) error); ok {
		r1 = rf(ctx, query, providerType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRosettaService_TranslateQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateQuery'
type MockRosettaService_TranslateQuery_Call struct {
	*mock.Call
}

// TranslateQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - providerType constants.ProviderType
func (_e *MockRosettaService_Expecter) TranslateQuery(ctx interface{}, query interface{}, providerType interface{}) *MockRosettaService_TranslateQuery_Call {
	return &MockRosettaService_TranslateQuery_Call{Call: _e.mock.On("TranslateQuery", ctx, query, providerType)}
}

func (_c *MockRosettaService_TranslateQuery_Call) Run(run func(ctx context.Context, query string, providerType constants.ProviderType)) *MockRosettaService_TranslateQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(constants.ProviderType))
	})
	return _c
}

func (_c *MockRosettaService_TranslateQuery_Call) Return(_a0 string, _a1 error) *MockRosettaService_TranslateQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRosettaService_TranslateQuery_Call) RunAndReturn(run func(context.Context, string, constants.ProviderType) (string, error)) *MockRosettaService_TranslateQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRosettaService creates a new instance of MockRosettaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRosettaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRosettaService {
	mock := &MockRosettaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
