global:
  service:
    name: hcp-dev

projectName: zamp  # required
default:
  annotations:
    all:
      app.kv.io/env: dev
  labels:
    all:
      service-name: hcp-dev
  resources:
    request:
      cpu: 300m
      memory: 800Mi
    limit:
      memory: 1000Mi
  replicaCount: 1
  image:
    repository:
    tag:
    imagePullPolicy: Always
  signoz:
    enabled: true
  configMaps:
    injection:
      enabled: false
    volumeMount:
      enabled: false
  externalSecrets:
    injection:
      enabled: true
      secrets:
      - secretName: env
        dataFrom:
          secretKey: zamp-dev-sg-hcp-secrets-env
        refreshInterval: 10m
        secretStoreName: gcp-secret-manager
    volumeMount:
      enabled: true
      secrets:
      - data:
          - fileName: ".temporal-key"
            mountPath: "/app/.temporal-key"
            secretKey: zamp-dev-sg-temporal-cert-key
        refreshInterval: 5m
        secretStoreName: gcp-secret-manager
        secretName: temporal-key
      - data:
          - fileName: ".temporal-cert"
            mountPath: "/app/.temporal-cert"
            secretKey: zamp-dev-sg-temporal-cert
        refreshInterval: 5m
        secretStoreName: gcp-secret-manager
        secretName: temporal-cert
deployment:
  - name: "api-worker-default"
    service:
      type: ClusterIP
      ports:
      - port: 8080
        name: api-worker-default
    serviceAccount:
      create: true
      annotations:
        iam.gke.io/gcp-service-account: zamp-dev-sg-hcp@development-351109.iam.gserviceaccount.com
    containers:
      - name: "api-worker-default"
        port: 8080
        env:
          POD_TYPE: "consumer"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
