

global:
  service:
    name: hcp-prd

projectName: zamp  # required
default:
  annotations:
    all:
      app.kv.io/env: prd
  labels:
    all:
      service-name: hcp-prd
  resources:
    request:
      cpu: 100m
      memory: 280Mi
    limit:
      memory: 320Mi
      cpu: 150m
  replicaCount: 1
  image:
    repository:
    tag:
    imagePullPolicy: Always
  signoz:
    enabled: true
  configMaps:
    injection:
      enabled: false
    volumeMount:
      enabled: false
  externalSecrets:
    injection:
      enabled: true
      secrets:
      - secretName: env
        dataFrom:
          secretKey: zamp-prd-us-hcp-secrets-env
        refreshInterval: 10m
        secretStoreName: gcp-secret-manager
    volumeMount:
      enabled: true
      secrets:
      - data:
          - fileName: ".temporal-key"
            mountPath: "/app/.temporal-key"
            secretKey: zamp-prd-sg-temporal-cert-key
        refreshInterval: 5m
        secretStoreName: gcp-secret-manager
        secretName: temporal-key
      - data:
          - fileName: ".temporal-cert"
            mountPath: "/app/.temporal-cert"
            secretKey: zamp-prd-sg-temporal-cert
        refreshInterval: 5m
        secretStoreName: gcp-secret-manager
        secretName: temporal-cert  
deployment:
  - name: "api-worker-ops"
    labels:
      app.kubernetes.io/component: herm
    service:
      type: ClusterIP
      ports:
      - port: 8080
        name: api-worker-ops
    serviceAccount:
      create: true
      annotations:
        iam.gke.io/gcp-service-account: zamp-prd-us-hcp@production-351109.iam.gserviceaccount.com
    containers:
      - name: "api-worker-ops"
        port: 8080
        env:
          POD_TYPE: "consumer"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80