global:
  service:
    name: hcp-stg

projectName: zamp  # required
default:
  annotations:
    all:
      app.kv.io/env: stg
  labels:
    all:
      service-name: hcp-stg
  resources:
    request:
      cpu: 50m
      memory: 50Mi
    limit:
      memory: 100Mi
  replicaCount: 1
  image:
    repository:
    tag:
    imagePullPolicy: Always
  signoz:
    enabled: true
  configMaps:
    injection:
      enabled: false
    volumeMount:
      enabled: false
  externalSecrets:
    injection:
      enabled: true
      secrets:
      - secretName: env
        dataFrom:
          secretKey: zamp-stg-sg-hcp-secrets-env
        refreshInterval: 10m
        secretStoreName: gcp-secret-manager
    volumeMount:
      enabled: true
job:
  - name: "app-migrations"
    serviceAccount:
      create: true
      annotations:
        iam.gke.io/gcp-service-account: zamp-stg-sg-hcp@staging-351109.iam.gserviceaccount.com
    containers:
      - name: app-migrations
        command:
          - /migrations/execute.sh
        env:
          POD_TYPE: "job"
    jobRestartPolicy: "OnFailure"
    startingDeadlineSeconds: "60"
    terminationGracePeriodSeconds: 30


