// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock_sheets

import (
	context "context"

	dbmodels "github.com/Zampfi/application-platform/services/api/db/models"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Zampfi/application-platform/services/api/core/sheets/models"

	uuid "github.com/google/uuid"
)

// MockSheetsService is an autogenerated mock type for the SheetsService type
type MockSheetsService struct {
	mock.Mock
}

type MockSheetsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSheetsService) EXPECT() *MockSheetsService_Expecter {
	return &MockSheetsService_Expecter{mock: &_m.Mock}
}

// CreateSheet provides a mock function with given fields: ctx, sheet
func (_m *MockSheetsService) CreateSheet(ctx context.Context, sheet models.Sheet) (*dbmodels.Sheet, error) {
	ret := _m.Called(ctx, sheet)

	if len(ret) == 0 {
		panic("no return value specified for CreateSheet")
	}

	var r0 *dbmodels.Sheet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Sheet) (*dbmodels.Sheet, error)); ok {
		return rf(ctx, sheet)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Sheet) *dbmodels.Sheet); ok {
		r0 = rf(ctx, sheet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodels.Sheet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Sheet) error); ok {
		r1 = rf(ctx, sheet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSheetsService_CreateSheet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSheet'
type MockSheetsService_CreateSheet_Call struct {
	*mock.Call
}

// CreateSheet is a helper method to define mock.On call
//   - ctx context.Context
//   - sheet models.Sheet
func (_e *MockSheetsService_Expecter) CreateSheet(ctx interface{}, sheet interface{}) *MockSheetsService_CreateSheet_Call {
	return &MockSheetsService_CreateSheet_Call{Call: _e.mock.On("CreateSheet", ctx, sheet)}
}

func (_c *MockSheetsService_CreateSheet_Call) Run(run func(ctx context.Context, sheet models.Sheet)) *MockSheetsService_CreateSheet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Sheet))
	})
	return _c
}

func (_c *MockSheetsService_CreateSheet_Call) Return(_a0 *dbmodels.Sheet, _a1 error) *MockSheetsService_CreateSheet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSheetsService_CreateSheet_Call) RunAndReturn(run func(context.Context, models.Sheet) (*dbmodels.Sheet, error)) *MockSheetsService_CreateSheet_Call {
	_c.Call.Return(run)
	return _c
}

// GetSheetById provides a mock function with given fields: ctx, pageId
func (_m *MockSheetsService) GetSheetById(ctx context.Context, pageId uuid.UUID) (*dbmodels.Sheet, error) {
	ret := _m.Called(ctx, pageId)

	if len(ret) == 0 {
		panic("no return value specified for GetSheetById")
	}

	var r0 *dbmodels.Sheet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dbmodels.Sheet, error)); ok {
		return rf(ctx, pageId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dbmodels.Sheet); ok {
		r0 = rf(ctx, pageId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodels.Sheet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pageId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSheetsService_GetSheetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSheetById'
type MockSheetsService_GetSheetById_Call struct {
	*mock.Call
}

// GetSheetById is a helper method to define mock.On call
//   - ctx context.Context
//   - pageId uuid.UUID
func (_e *MockSheetsService_Expecter) GetSheetById(ctx interface{}, pageId interface{}) *MockSheetsService_GetSheetById_Call {
	return &MockSheetsService_GetSheetById_Call{Call: _e.mock.On("GetSheetById", ctx, pageId)}
}

func (_c *MockSheetsService_GetSheetById_Call) Run(run func(ctx context.Context, pageId uuid.UUID)) *MockSheetsService_GetSheetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSheetsService_GetSheetById_Call) Return(_a0 *dbmodels.Sheet, _a1 error) *MockSheetsService_GetSheetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSheetsService_GetSheetById_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dbmodels.Sheet, error)) *MockSheetsService_GetSheetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetSheetFilterConfigById provides a mock function with given fields: ctx, orgId, sheetId
func (_m *MockSheetsService) GetSheetFilterConfigById(ctx context.Context, orgId uuid.UUID, sheetId uuid.UUID) (*models.FilterOptionsConfig, error) {
	ret := _m.Called(ctx, orgId, sheetId)

	if len(ret) == 0 {
		panic("no return value specified for GetSheetFilterConfigById")
	}

	var r0 *models.FilterOptionsConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.FilterOptionsConfig, error)); ok {
		return rf(ctx, orgId, sheetId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.FilterOptionsConfig); ok {
		r0 = rf(ctx, orgId, sheetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FilterOptionsConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, orgId, sheetId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSheetsService_GetSheetFilterConfigById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSheetFilterConfigById'
type MockSheetsService_GetSheetFilterConfigById_Call struct {
	*mock.Call
}

// GetSheetFilterConfigById is a helper method to define mock.On call
//   - ctx context.Context
//   - orgId uuid.UUID
//   - sheetId uuid.UUID
func (_e *MockSheetsService_Expecter) GetSheetFilterConfigById(ctx interface{}, orgId interface{}, sheetId interface{}) *MockSheetsService_GetSheetFilterConfigById_Call {
	return &MockSheetsService_GetSheetFilterConfigById_Call{Call: _e.mock.On("GetSheetFilterConfigById", ctx, orgId, sheetId)}
}

func (_c *MockSheetsService_GetSheetFilterConfigById_Call) Run(run func(ctx context.Context, orgId uuid.UUID, sheetId uuid.UUID)) *MockSheetsService_GetSheetFilterConfigById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockSheetsService_GetSheetFilterConfigById_Call) Return(_a0 *models.FilterOptionsConfig, _a1 error) *MockSheetsService_GetSheetFilterConfigById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSheetsService_GetSheetFilterConfigById_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.FilterOptionsConfig, error)) *MockSheetsService_GetSheetFilterConfigById_Call {
	_c.Call.Return(run)
	return _c
}

// GetSheetsByPageId provides a mock function with given fields: ctx, pageId
func (_m *MockSheetsService) GetSheetsByPageId(ctx context.Context, pageId uuid.UUID) ([]dbmodels.Sheet, error) {
	ret := _m.Called(ctx, pageId)

	if len(ret) == 0 {
		panic("no return value specified for GetSheetsByPageId")
	}

	var r0 []dbmodels.Sheet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dbmodels.Sheet, error)); ok {
		return rf(ctx, pageId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dbmodels.Sheet); ok {
		r0 = rf(ctx, pageId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbmodels.Sheet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pageId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSheetsService_GetSheetsByPageId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSheetsByPageId'
type MockSheetsService_GetSheetsByPageId_Call struct {
	*mock.Call
}

// GetSheetsByPageId is a helper method to define mock.On call
//   - ctx context.Context
//   - pageId uuid.UUID
func (_e *MockSheetsService_Expecter) GetSheetsByPageId(ctx interface{}, pageId interface{}) *MockSheetsService_GetSheetsByPageId_Call {
	return &MockSheetsService_GetSheetsByPageId_Call{Call: _e.mock.On("GetSheetsByPageId", ctx, pageId)}
}

func (_c *MockSheetsService_GetSheetsByPageId_Call) Run(run func(ctx context.Context, pageId uuid.UUID)) *MockSheetsService_GetSheetsByPageId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSheetsService_GetSheetsByPageId_Call) Return(_a0 []dbmodels.Sheet, _a1 error) *MockSheetsService_GetSheetsByPageId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSheetsService_GetSheetsByPageId_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]dbmodels.Sheet, error)) *MockSheetsService_GetSheetsByPageId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSheet provides a mock function with given fields: ctx, sheet
func (_m *MockSheetsService) UpdateSheet(ctx context.Context, sheet *models.Sheet) (*dbmodels.Sheet, error) {
	ret := _m.Called(ctx, sheet)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSheet")
	}

	var r0 *dbmodels.Sheet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Sheet) (*dbmodels.Sheet, error)); ok {
		return rf(ctx, sheet)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Sheet) *dbmodels.Sheet); ok {
		r0 = rf(ctx, sheet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodels.Sheet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Sheet) error); ok {
		r1 = rf(ctx, sheet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSheetsService_UpdateSheet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSheet'
type MockSheetsService_UpdateSheet_Call struct {
	*mock.Call
}

// UpdateSheet is a helper method to define mock.On call
//   - ctx context.Context
//   - sheet *models.Sheet
func (_e *MockSheetsService_Expecter) UpdateSheet(ctx interface{}, sheet interface{}) *MockSheetsService_UpdateSheet_Call {
	return &MockSheetsService_UpdateSheet_Call{Call: _e.mock.On("UpdateSheet", ctx, sheet)}
}

func (_c *MockSheetsService_UpdateSheet_Call) Run(run func(ctx context.Context, sheet *models.Sheet)) *MockSheetsService_UpdateSheet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Sheet))
	})
	return _c
}

func (_c *MockSheetsService_UpdateSheet_Call) Return(_a0 *dbmodels.Sheet, _a1 error) *MockSheetsService_UpdateSheet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSheetsService_UpdateSheet_Call) RunAndReturn(run func(context.Context, *models.Sheet) (*dbmodels.Sheet, error)) *MockSheetsService_UpdateSheet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSheetsService creates a new instance of MockSheetsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSheetsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSheetsService {
	mock := &MockSheetsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
